### ISSUE TITLE
Black Duck scan gives this repo a 1/10 rating

### ISSUE THREAD

**Issue by matttrawicki** [blackducksoftware/hub-teamcity#21]
I was asked by someone to install this plugin on my TeamCity server. I cannot even consider it when your own scan tool gives it the lowest possible score.

**Comment by stavvy-akamen** [comment]
@matttrawicki That is true, we have not updated TeamCity in a while and as the vulnerability information updates the picture 'worsens'.  However the reason we stopped updating is because we want people to switch to Detect:  https://github.com/blackducksoftware/hub-detect/

Can you please consider using Detect.
